# Github action building the project with different versions of Java and uploading the test coverage to Coveralls.

name: build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

env:
  STOREPASS: password

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11, 17, 21 ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Compile
        run: |
          mvn -version
          mvn -B clean compile

      - name: Tests
        run: mvn -B test

      - name: Packaging
        run: mvn -B package -DskipTests

      - name: Coverage report
        if: ${{ matrix.java == '17' }}
        run: mvn -B clean test jacoco:report-aggregate coveralls:report -DjacocoReports=jsign/target/site/jacoco-aggregate/jacoco.xml -DrepoToken=${{ secrets.COVERALLS_TOKEN }} || true

  experimental:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: 'Set up Java EA'
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: EA
          cache: 'maven'          

      - name: Build
        run: |
          mvn -version
          mvn -B clean package || true
